import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { desktopApi } from "@/lib/desktop-api";
import type { KnowledgeEntityType } from "@/lib/desktop-api/knowledge-graph";

const keys = { all: ["knowledge-graph"] as const, entities: (workspaceId: string) => [...keys.all, "entities", workspaceId] as const, relationships: (workspaceId: string) => [...keys.all, "relationships", workspaceId] as const, links: (thesisId: string) => [...keys.all, "links", thesisId] as const };
export function useKnowledgeEntities(workspaceId: string) { return useQuery({ queryKey: keys.entities(workspaceId), queryFn: () => desktopApi.knowledgeGraph.listKnowledgeEntities(workspaceId), enabled: Boolean(workspaceId) }); }
export function useKnowledgeRelationships(workspaceId: string) { return useQuery({ queryKey: keys.relationships(workspaceId), queryFn: () => desktopApi.knowledgeGraph.listKnowledgeRelationships(workspaceId), enabled: Boolean(workspaceId) }); }
export function useThesisKnowledgeLinks(thesisId: string) { return useQuery({ queryKey: keys.links(thesisId), queryFn: () => desktopApi.knowledgeGraph.listThesisKnowledgeLinks(thesisId), enabled: Boolean(thesisId) }); }
export function useCreateKnowledgeEntity() { const client = useQueryClient(); return useMutation({ mutationFn: ({ workspaceId, entityType, name, description }: { workspaceId: string; entityType: KnowledgeEntityType; name: string; description?: string }) => desktopApi.knowledgeGraph.createKnowledgeEntity(workspaceId, entityType, name, description), onSuccess: (_, input) => client.invalidateQueries({ queryKey: keys.entities(input.workspaceId) }) }); }
export function useCreateKnowledgeRelationship() { const client = useQueryClient(); return useMutation({ mutationFn: ({ sourceEntityId, targetEntityId, relationshipType }: { sourceEntityId: string; targetEntityId: string; relationshipType: string }) => desktopApi.knowledgeGraph.createKnowledgeRelationship(sourceEntityId, targetEntityId, relationshipType), onSuccess: () => client.invalidateQueries({ queryKey: keys.all }) }); }
export function useLinkThesisKnowledgeEntity() { const client = useQueryClient(); return useMutation({ mutationFn: ({ thesisId, entityId }: { thesisId: string; entityId: string }) => desktopApi.knowledgeGraph.linkThesisKnowledgeEntity(thesisId, entityId), onSuccess: () => client.invalidateQueries({ queryKey: keys.all }) }); }
