// Proposal domain models for human-approved agent suggestions (M10-G4).
//
// These represent structured suggestions generated by Goose (e.g. evidence links,
// research notes) that require explicit human review and approval before being persisted
// to domain tables. No proposal can autonomously modify portfolios or execute trades.

use serde::{Deserialize, Serialize};

/// Type of proposal generated by the agent
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProposalType {
    /// Evidence link proposal for an investment thesis
    EvidenceCandidate,
    /// Note proposal for a research document
    ResearchNote,
    /// Report outline proposal
    ReportOutline,
}

/// Status of a proposal lifecycle
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProposalStatus {
    /// Waiting for human review
    Pending,
    /// Explicitly accepted and committed by human
    Accepted,
    /// Rejected by human
    Rejected,
}

/// A structured proposal generated by Goose
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Proposal {
    /// Unique proposal ID (UUID)
    pub id: String,
    /// Workspace ID
    pub workspace_id: String,
    /// Associated Goose execution run ID for provenance
    pub run_id: String,
    /// Type of proposal
    pub proposal_type: ProposalType,
    /// Human-readable title
    pub title: String,
    /// Summary or rationale
    pub summary: String,
    /// Structured payload (e.g. EvidenceCandidatePayload, ResearchNotePayload)
    pub payload: serde_json::Value,
    /// Current review status
    pub status: ProposalStatus,
    /// ISO 8601 creation timestamp
    pub created_at: String,
    /// ISO 8601 review timestamp (if accepted/rejected)
    pub reviewed_at: Option<String>,
    /// Resulting domain entity ID created upon acceptance (e.g. thesis_evidence id, note id)
    pub resulting_entity_id: Option<String>,
}

/// Payload for an evidence candidate proposal
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceCandidatePayload {
    /// Thesis ID to link evidence to
    pub thesis_id: String,
    /// Source document/entity ID
    pub source_id: String,
    /// Relevant excerpt from source
    pub excerpt: String,
    /// Relation to thesis: supports or contradicts
    pub relation: String,
    /// Confidence percentage (0-100)
    pub confidence: Option<u8>,
}

/// Payload for a research note proposal
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResearchNotePayload {
    /// Research document ID to attach note to
    pub document_id: String,
    /// Content of the note
    pub content: String,
}

/// Input for creating a proposal
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateProposalInput {
    pub workspace_id: String,
    pub run_id: String,
    pub proposal_type: ProposalType,
    pub title: String,
    pub summary: String,
    pub payload: serde_json::Value,
}
