// Financial repositories — assets + quotes.
//
// SQLx persistence for the financial `assets` and `quotes` tables
// (migration 0016). `instrument_key` is generated by the storage engine and
// never written by the application.

use chrono::Utc;
use sqlx::SqlitePool;

use crate::database::repositories::financial_support::{
    parse_date, parse_decimal, parse_json, parse_optional_decimal, parse_timestamp,
};
use crate::error::AppError;
use domain::financial::{Asset, CreateAssetInput, Quote, UpsertQuoteInput};

pub struct AssetRepository {
    pool: SqlitePool,
}

impl AssetRepository {
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn create(&self, input: CreateAssetInput) -> Result<Asset, AppError> {
        let id = uuid::Uuid::new_v4().to_string();
        let now = Utc::now();

        sqlx::query(
            "INSERT INTO assets
                (id, kind, name, display_code, notes, is_active, quote_mode,
                 quote_ccy, instrument_type, instrument_symbol, instrument_exchange_mic,
                 provider_config, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .bind(&id)
        .bind(input.kind.to_string())
        .bind(&input.name)
        .bind(&input.display_code)
        .bind(&input.notes)
        .bind(input.is_active)
        .bind(input.quote_mode.to_string())
        .bind(&input.quote_ccy)
        .bind(input.instrument_type.map(|t| t.to_string()))
        .bind(&input.instrument_symbol)
        .bind(&input.instrument_exchange_mic)
        .bind(json_or_null(&input.provider_config))
        .bind(now.to_rfc3339())
        .bind(now.to_rfc3339())
        .execute(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to create asset: {e}")))?;

        let row = sqlx::query_as::<_, AssetRow>(
            "SELECT id, kind, name, display_code, notes, metadata, is_active, quote_mode,
                    quote_ccy, instrument_type, instrument_symbol, instrument_exchange_mic,
                    instrument_key, provider_config, created_at, updated_at
             FROM assets WHERE id = ?",
        )
        .bind(&id)
        .fetch_one(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to read created asset: {e}")))?;

        row.try_into()
    }

    pub async fn get(&self, id: &str) -> Result<Option<Asset>, AppError> {
        let row = sqlx::query_as::<_, AssetRow>(
            "SELECT id, kind, name, display_code, notes, metadata, is_active, quote_mode,
                    quote_ccy, instrument_type, instrument_symbol, instrument_exchange_mic,
                    instrument_key, provider_config, created_at, updated_at
             FROM assets WHERE id = ?",
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to get asset: {e}")))?;

        row.map(TryInto::try_into).transpose()
    }

    pub async fn find_by_instrument_key(
        &self,
        instrument_key: &str,
    ) -> Result<Option<Asset>, AppError> {
        let row = sqlx::query_as::<_, AssetRow>(
            "SELECT id, kind, name, display_code, notes, metadata, is_active, quote_mode,
                    quote_ccy, instrument_type, instrument_symbol, instrument_exchange_mic,
                    instrument_key, provider_config, created_at, updated_at
             FROM assets WHERE instrument_key = ?",
        )
        .bind(instrument_key)
        .fetch_optional(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to find asset by instrument key: {e}")))?;

        row.map(TryInto::try_into).transpose()
    }

    pub async fn list_active(&self) -> Result<Vec<Asset>, AppError> {
        let rows = sqlx::query_as::<_, AssetRow>(
            "SELECT id, kind, name, display_code, notes, metadata, is_active, quote_mode,
                    quote_ccy, instrument_type, instrument_symbol, instrument_exchange_mic,
                    instrument_key, provider_config, created_at, updated_at
             FROM assets WHERE is_active = 1 ORDER BY display_code, name",
        )
        .fetch_all(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to list active assets: {e}")))?;

        rows.into_iter().map(TryInto::try_into).collect()
    }
}

pub struct QuoteRepository {
    pool: SqlitePool,
}

impl QuoteRepository {
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// Inserts a quote or updates the existing row for (asset, day, source).
    /// Returns the effective row whether inserted or updated.
    pub async fn upsert(&self, input: UpsertQuoteInput) -> Result<Quote, AppError> {
        let id = uuid::Uuid::new_v4().to_string();
        let created_at = Utc::now();
        let timestamp = Utc::now();

        sqlx::query(
            "INSERT INTO quotes
                (id, asset_id, day, source, open, high, low, close, adjclose, volume,
                 currency, notes, created_at, timestamp)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
             ON CONFLICT(asset_id, day, source) DO UPDATE SET
                open = excluded.open,
                high = excluded.high,
                low = excluded.low,
                close = excluded.close,
                adjclose = excluded.adjclose,
                volume = excluded.volume,
                currency = excluded.currency,
                notes = excluded.notes,
                timestamp = excluded.timestamp",
        )
        .bind(&id)
        .bind(&input.asset_id)
        .bind(input.day.to_string())
        .bind(&input.source)
        .bind(input.open.map(|d| d.to_string()))
        .bind(input.high.map(|d| d.to_string()))
        .bind(input.low.map(|d| d.to_string()))
        .bind(input.close.to_string())
        .bind(input.adjclose.map(|d| d.to_string()))
        .bind(input.volume.map(|d| d.to_string()))
        .bind(&input.currency)
        .bind(&input.notes)
        .bind(created_at.to_rfc3339())
        .bind(timestamp.to_rfc3339())
        .execute(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to upsert quote: {e}")))?;

        self.get_for_day(&input.asset_id, &input.day, &input.source)
            .await?
            .ok_or_else(|| AppError::Internal("upserted quote disappeared".to_string()))
    }

    pub async fn get_for_day(
        &self,
        asset_id: &str,
        day: &chrono::NaiveDate,
        source: &str,
    ) -> Result<Option<Quote>, AppError> {
        let row = sqlx::query_as::<_, QuoteRow>(
            "SELECT id, asset_id, day, source, open, high, low, close, adjclose, volume,
                    currency, notes, created_at, timestamp
             FROM quotes WHERE asset_id = ? AND day = ? AND source = ?",
        )
        .bind(asset_id)
        .bind(day.to_string())
        .bind(source)
        .fetch_optional(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to get quote: {e}")))?;

        row.map(TryInto::try_into).transpose()
    }

    pub async fn list_for_asset(&self, asset_id: &str) -> Result<Vec<Quote>, AppError> {
        let rows = sqlx::query_as::<_, QuoteRow>(
            "SELECT id, asset_id, day, source, open, high, low, close, adjclose, volume,
                    currency, notes, created_at, timestamp
             FROM quotes WHERE asset_id = ? ORDER BY day",
        )
        .bind(asset_id)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| AppError::Internal(format!("failed to list quotes: {e}")))?;

        rows.into_iter().map(TryInto::try_into).collect()
    }
}

#[derive(sqlx::FromRow)]
struct AssetRow {
    id: String,
    kind: String,
    name: Option<String>,
    display_code: Option<String>,
    notes: Option<String>,
    metadata: Option<String>,
    is_active: bool,
    quote_mode: String,
    quote_ccy: String,
    instrument_type: Option<String>,
    instrument_symbol: Option<String>,
    instrument_exchange_mic: Option<String>,
    instrument_key: Option<String>,
    provider_config: Option<String>,
    created_at: String,
    updated_at: String,
}

impl TryFrom<AssetRow> for Asset {
    type Error = AppError;

    fn try_from(row: AssetRow) -> Result<Self, Self::Error> {
        let kind = domain::financial::AssetKind::parse(&row.kind).ok_or_else(|| {
            AppError::Internal(format!("invalid asset kind in database: {}", row.kind))
        })?;
        let quote_mode = domain::financial::QuoteMode::parse(&row.quote_mode).ok_or_else(|| {
            AppError::Internal(format!(
                "invalid quote_mode in database: {}",
                row.quote_mode
            ))
        })?;
        let instrument_type =
            match row.instrument_type.as_deref() {
                Some(raw) => Some(domain::financial::InstrumentType::parse(raw).ok_or_else(
                    || AppError::Internal(format!("invalid instrument_type in database: {raw}")),
                )?),
                None => None,
            };

        Ok(Self {
            id: row.id,
            kind,
            name: row.name,
            display_code: row.display_code,
            notes: row.notes,
            metadata: parse_json(row.metadata, "asset metadata")?,
            is_active: row.is_active,
            quote_mode,
            quote_ccy: row.quote_ccy,
            instrument_type,
            instrument_symbol: row.instrument_symbol,
            instrument_exchange_mic: row.instrument_exchange_mic,
            instrument_key: row.instrument_key,
            provider_config: parse_json(row.provider_config, "asset provider config")?,
            created_at: parse_timestamp(&row.created_at, "asset creation")?,
            updated_at: parse_timestamp(&row.updated_at, "asset update")?,
        })
    }
}

#[derive(sqlx::FromRow)]
struct QuoteRow {
    id: String,
    asset_id: String,
    day: String,
    source: String,
    open: Option<String>,
    high: Option<String>,
    low: Option<String>,
    close: String,
    adjclose: Option<String>,
    volume: Option<String>,
    currency: String,
    notes: Option<String>,
    created_at: String,
    timestamp: String,
}

impl TryFrom<QuoteRow> for Quote {
    type Error = AppError;

    fn try_from(row: QuoteRow) -> Result<Self, Self::Error> {
        Ok(Self {
            id: row.id,
            asset_id: row.asset_id,
            day: parse_date(&row.day, "quote day")?,
            source: row.source,
            open: parse_optional_decimal(row.open, "quote open")?,
            high: parse_optional_decimal(row.high, "quote high")?,
            low: parse_optional_decimal(row.low, "quote low")?,
            close: parse_decimal(&row.close, "quote close")?,
            adjclose: parse_optional_decimal(row.adjclose, "quote adjclose")?,
            volume: parse_optional_decimal(row.volume, "quote volume")?,
            currency: row.currency,
            notes: row.notes,
            created_at: parse_timestamp(&row.created_at, "quote creation")?,
            timestamp: parse_timestamp(&row.timestamp, "quote timestamp")?,
        })
    }
}

fn json_or_null(value: &Option<serde_json::Value>) -> Option<String> {
    value.as_ref().map(serde_json::Value::to_string)
}
