-- Financial domain schema (Phase 1 storage) — platforms + accounts.
--
-- Ported from Wealthfolio (AGPL-3.0, crates/storage-sqlite/migrations) onto
-- SQLx conventions used by this repository:
--
--   * Money and quantity values are TEXT (decimal strings, parsed as
--     rust_decimal in Rust) — never REAL.
--   * Timestamps are TEXT in RFC3339 UTC (strftime('%Y-%m-%dT%H:%M:%fZ','now')).
--   * Primary keys are TEXT UUID v4 generated by the application layer.
--
-- Deliberate Investment OS deviation: `accounts.workspace_id` (nullable FK to
-- workspaces) scopes financial accounts to a research workspace, matching the
-- existing placeholder portfolio model. Wealthfolio has no workspace concept.
--
-- The pre-existing placeholder tables (portfolio_accounts, positions,
-- transactions) are left untouched; this financial schema is the canonical
-- replacement and the placeholder UI is retired in Phase 3.

CREATE TABLE IF NOT EXISTS platforms (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT,
    url TEXT NOT NULL,
    external_id TEXT,
    kind TEXT NOT NULL DEFAULT 'BROKERAGE',
    website_url TEXT,
    logo_url TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY NOT NULL,
    -- Investment OS extension: scopes the account to a research workspace.
    workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    account_type TEXT NOT NULL CHECK (account_type IN (
        'SECURITIES', 'CASH', 'CREDIT_CARD', 'CRYPTOCURRENCY'
    )),
    group_name TEXT,
    currency TEXT NOT NULL,
    is_default INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    platform_id TEXT REFERENCES platforms(id) ON DELETE SET NULL ON UPDATE CASCADE,
    account_number TEXT,
    meta TEXT CHECK (meta IS NULL OR json_valid(meta)),
    provider TEXT,
    provider_account_id TEXT,
    is_archived INTEGER NOT NULL DEFAULT 0,
    tracking_mode TEXT NOT NULL DEFAULT 'TRANSACTIONS' CHECK (tracking_mode IN (
        'NOT_SET', 'TRANSACTIONS', 'HOLDINGS'
    )),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    CHECK (is_default IN (0, 1)),
    CHECK (is_active IN (0, 1)),
    CHECK (is_archived IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_accounts_workspace
    ON accounts(workspace_id)
    WHERE workspace_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_accounts_platform
    ON accounts(platform_id)
    WHERE platform_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_accounts_provider
    ON accounts(provider, provider_account_id)
    WHERE provider IS NOT NULL;
